add_test([=[ringbuffer.initial_length_is_0]=]  /workspace/ringbuffer.cpp/bin/unit_tests [==[--gtest_filter=ringbuffer.initial_length_is_0]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ringbuffer.initial_length_is_0]=]  PROPERTIES WORKING_DIRECTORY /workspace/ringbuffer.cpp/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] LABELS unit)
add_test([=[ringbuffer.adding_increses_len]=]  /workspace/ringbuffer.cpp/bin/unit_tests [==[--gtest_filter=ringbuffer.adding_increses_len]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ringbuffer.adding_increses_len]=]  PROPERTIES WORKING_DIRECTORY /workspace/ringbuffer.cpp/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] LABELS unit)
add_test([=[ringbuffer.can_only_add_max_length_elements]=]  /workspace/ringbuffer.cpp/bin/unit_tests [==[--gtest_filter=ringbuffer.can_only_add_max_length_elements]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ringbuffer.can_only_add_max_length_elements]=]  PROPERTIES WORKING_DIRECTORY /workspace/ringbuffer.cpp/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] LABELS unit)
add_test([=[ringbuffer.reading_returns_items_in_order]=]  /workspace/ringbuffer.cpp/bin/unit_tests [==[--gtest_filter=ringbuffer.reading_returns_items_in_order]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ringbuffer.reading_returns_items_in_order]=]  PROPERTIES WORKING_DIRECTORY /workspace/ringbuffer.cpp/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] LABELS unit)
add_test([=[ringbuffer.reading_after_wrap_around]=]  /workspace/ringbuffer.cpp/bin/unit_tests [==[--gtest_filter=ringbuffer.reading_after_wrap_around]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ringbuffer.reading_after_wrap_around]=]  PROPERTIES WORKING_DIRECTORY /workspace/ringbuffer.cpp/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] LABELS unit)
add_test([=[ringbuffer.reading_empty_buffer_returns_false]=]  /workspace/ringbuffer.cpp/bin/unit_tests [==[--gtest_filter=ringbuffer.reading_empty_buffer_returns_false]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ringbuffer.reading_empty_buffer_returns_false]=]  PROPERTIES WORKING_DIRECTORY /workspace/ringbuffer.cpp/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] LABELS unit)
add_test([=[ringbuffer.adding_a_lot_of_entries]=]  /workspace/ringbuffer.cpp/bin/unit_tests [==[--gtest_filter=ringbuffer.adding_a_lot_of_entries]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ringbuffer.adding_a_lot_of_entries]=]  PROPERTIES WORKING_DIRECTORY /workspace/ringbuffer.cpp/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] LABELS unit)
set(  unit_tests_TESTS ringbuffer.initial_length_is_0 ringbuffer.adding_increses_len ringbuffer.can_only_add_max_length_elements ringbuffer.reading_returns_items_in_order ringbuffer.reading_after_wrap_around ringbuffer.reading_empty_buffer_returns_false ringbuffer.adding_a_lot_of_entries)
